#!/usr/bin/env node
/* Record how long each narration runs, into audio/manifest.json:
     node canon/scripts/durations.mjs
   speak.mjs does this for what it renders; run it by hand to backfill files
   that were rendered before. */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { durationOf } from './mp3.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const dir = path.join(here, '..', 'audio');
const manifestPath = path.join(dir, 'manifest.json');

let manifest = {};
try { manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8')); } catch {}

const files = (await fs.readdir(dir)).filter((f) => f.endsWith('.mp3')).sort();
for (const file of files) {
  const id = file.replace(/\.mp3$/, '');
  const seconds = durationOf(await fs.readFile(path.join(dir, file)));
  manifest[id] = { ...(manifest[id] || {}), seconds: Math.round(seconds * 100) / 100 };
  console.log(`${id.padEnd(34)} ${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`);
}
await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2) + '\n');

/* Which works can actually be heard. The rotation reads this and draws only
   from recorded works while any are unrecorded, so a reader is never handed the
   browser voice because the day happened to land on a silent one. Render the
   rest and re-run: the list grows, and when it covers the catalogue the
   rotation is back to drawing from all of it. */
const ids = files.map((f) => f.replace(/\.mp3$/, '')).sort();
await fs.writeFile(path.join(here, '..', 'narrated.js'),
  '/* Generated by scripts/durations.mjs — do not edit by hand.\n'
  + '   The works with a rendered narration. The daily rotation draws only from\n'
  + '   these for as long as some of the catalogue is unrecorded. */\n'
  + 'const NARRATED = ' + JSON.stringify(ids, null, 1) + ';\n'
  + "if (typeof window !== 'undefined') window.NARRATED = NARRATED;\n"
  + "if (typeof module !== 'undefined') module.exports = { NARRATED };\n");

console.log(`\n${files.length} files timed, and listed in narrated.js.`);
