/* Generated by scripts/durations.mjs — do not edit by hand.
   The works with a rendered narration. The daily rotation draws only from
   these for as long as some of the catalogue is unrecorded. */
const NARRATED = [
 "american-gothic",
 "arnolfini-portrait",
 "bal-du-moulin-de-la-galette",
 "birth-of-venus",
 "black-square",
 "calling-of-saint-matthew",
 "card-players",
 "composition-red-blue-yellow",
 "composition-vii",
 "creation-of-adam",
 "dance",
 "death-of-marat",
 "dejeuner-sur-lherbe",
 "fighting-temeraire",
 "garden-of-earthly-delights",
 "girl-with-a-pearl-earring",
 "grande-jatte",
 "great-wave",
 "impression-sunrise",
 "las-meninas",
 "last-supper",
 "liberty-leading-the-people",
 "mona-lisa",
 "night-watch",
 "nighthawks",
 "raft-of-the-medusa",
 "school-of-athens",
 "starry-night",
 "the-kiss",
 "the-scream",
 "third-of-may-1808",
 "wanderer-above-the-sea-of-fog"
];
if (typeof window !== 'undefined') window.NARRATED = NARRATED;
if (typeof module !== 'undefined') module.exports = { NARRATED };
