/* Generated by scripts/references.mjs — do not edit by hand.
   Maps each reference label to the Wikipedia article it names and, where
   there is one, the Wikimedia image file for it. */
const REFERENCES = {
 "Velázquez, Las Meninas (1656)": {
  "page": "Las Meninas",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg/3840px-Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Pablo Picasso, Las Meninas (1957)": {
  "page": "Las Meninas",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg/3840px-Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "David Hockney, Secret Knowledge (2001)": {
  "page": "Hockney–Falco thesis",
  "image": "https://upload.wikimedia.org/wikipedia/commons/8/85/1646_Athanasius_Kircher_-_Camera_obscura.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Erwin Panofsky (1934)": {
  "page": "Erwin Panofsky",
  "image": "https://upload.wikimedia.org/wikipedia/commons/6/65/Erwin_Panofsky_at_Oberlin_College_%281950%29_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Homeric Hymn to Aphrodite; Poliziano’s Stanze": {
  "page": "Homeric Hymns",
  "image": "https://upload.wikimedia.org/wikipedia/commons/d/df/Exekias_Dionysos_Staatliche_Antikensammlungen_2044.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Andy Warhol, Details of Renaissance Paintings (1984)": {
  "page": "List of most expensive paintings",
  "image": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Leonardo_da_Vinci%2C_Salvator_Mundi%2C_c.1500%2C_oil_on_walnut%2C_45.4_%C3%97_65.6_cm.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Adobe Illustrator splash screen (1987 – 2010s)": {
  "page": "Adobe Illustrator",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Adobe_Illustrator_CC_icon.svg/3840px-Adobe_Illustrator_CC_icon.svg.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Uma Thurman in The Adventures of Baron Munchausen (1988)": {
  "page": "The Adventures of Baron Munchausen"
 },
 "Gospel of John 13:21": {
  "page": "Gospel of John",
  "image": "https://upload.wikimedia.org/wikipedia/commons/d/dd/JRL19060215_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Andy Warhol, The Last Supper series (1986)": {
  "page": "Last Supper (Warhol)"
 },
 "Luis Buñuel, Viridiana (1961)": {
  "page": "Viridiana"
 },
 "Dan Brown, The Da Vinci Code (2003)": {
  "page": "The Da Vinci Code"
 },
 "Marcel Duchamp, L.H.O.O.Q. (1919)": {
  "page": "L.H.O.O.Q.",
  "image": "https://upload.wikimedia.org/wikipedia/en/7/74/Marcel_Duchamp%2C_1919%2C_L.H.O.O.Q.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Andy Warhol, Thirty Are Better Than One (1963)": {
  "page": "Andy Warhol",
  "image": "https://upload.wikimedia.org/wikipedia/commons/6/6c/Andy_Warhol_by_Bernard_Gotfryd_1980.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Nat King Cole, “Mona Lisa” (1950)": {
  "page": "Mona Lisa",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/3840px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Walter Pater, The Renaissance (1873)": {
  "page": "Renaissance",
  "image": "https://upload.wikimedia.org/wikipedia/commons/2/22/Da_Vinci_Vitruve_Luc_Viatour.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Genesis 1:27; Lorenzo Ghiberti’s Gates of Paradise (1425 – 52)": {
  "page": "Image of God"
 },
 "E.T. the Extra-Terrestrial poster (1982)": {
  "page": "E.T. the Extra-Terrestrial"
 },
 "Frank Meshberger, JAMA (1990)": {
  "page": "JAMA"
 },
 "Nokia’s 1990s “Connecting People” logo": {
  "page": "Nokia",
  "image": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Midpoint_Nokia_Karaportti.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Plato, Timaeus; Aristotle, Nicomachean Ethics": {
  "page": "Timaeus"
 },
 "Bramante’s St Peter’s": {
  "page": "Donato Bramante",
  "image": "https://upload.wikimedia.org/wikipedia/commons/3/35/Donato_Bramante.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "The Athenaeum of countless universities": {
  "search": "The Athenaeum of countless universities"
 },
 "Pieter Bruegel the Elder": {
  "page": "Pieter Bruegel the Elder",
  "image": "https://upload.wikimedia.org/wikipedia/commons/2/28/Pieter_Bruegel_the_Elder_-_The_Painter_and_the_Buyer%2C_ca._1566_-_Google_Art_Project.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Salvador Dalí and the Surrealists": {
  "page": "Salvador Dalí",
  "image": "https://upload.wikimedia.org/wikipedia/commons/2/24/Salvador_Dal%C3%AD_1939.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "The music written on a sinner’s buttocks": {
  "search": "The music written on a sinner’s buttocks"
 },
 "Michael Jackson, Dangerous album cover (1991)": {
  "page": "Dangerous (Michael Jackson album)"
 },
 "Gospel of Matthew 9:9": {
  "page": "Matthew 9",
  "image": "https://upload.wikimedia.org/wikipedia/commons/c/c9/Codex_Sinaiticus_Matthew_8%2C28-9%2C23.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Michelangelo, The Creation of Adam": {
  "page": "The Creation of Adam",
  "image": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Rembrandt, Georges de La Tour, Artemisia Gentileschi": {
  "page": "Rembrandt",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bd/Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg/3840px-Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Pope Francis (2013)": {
  "page": "Pope Francis",
  "image": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Pope_Francis_Korea_Haemi_Castle_19_%284x5_cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Frans Hals’s militia pieces": {
  "page": "Frans Hals",
  "image": "https://upload.wikimedia.org/wikipedia/commons/3/3b/After_Frans_Hals_-_Portrait_of_Frans_Hals_-_Indianapolis.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Peter Greenaway, Nightwatching (2007)": {
  "page": "Nightwatching"
 },
 "Operation Night Watch (2019 – )": {
  "page": "The Night Watch",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/La_ronda_de_noche%2C_por_Rembrandt_van_Rijn.jpg/3840px-La_ronda_de_noche%2C_por_Rembrandt_van_Rijn.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Rijksmuseum flash mob (2013)": {
  "search": "Rijksmuseum flash mob"
 },
 "Jan van Eyck, The Arnolfini Portrait (1434)": {
  "page": "Arnolfini Portrait",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/The_Arnolfini_portrait_%281434%29.jpg/3840px-The_Arnolfini_portrait_%281434%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Michel Foucault, The Order of Things (1966)": {
  "page": "The Order of Things"
 },
 "Salvador Dalí, Francis Bacon, Joel-Peter Witkin": {
  "page": "Salvador Dalí",
  "image": "https://upload.wikimedia.org/wikipedia/commons/2/24/Salvador_Dal%C3%AD_1939.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Tracy Chevalier, Girl with a Pearl Earring (1999); film (2003)": {
  "page": "Girl with a Pearl Earring",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/3840px-1665_Girl_with_a_Pearl_Earring.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Banksy, Girl with a Pierced Eardrum (2014)": {
  "page": "Girl with a Pierced Eardrum"
 },
 "Vermeer, Mauritshuis (2023)": {
  "page": "Mauritshuis",
  "image": "https://upload.wikimedia.org/wikipedia/commons/e/e9/Mauritshuis_museum_logo.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Michelangelo, Pietà (1499)": {
  "page": "Pietà",
  "image": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Michelangelo%27s_Pieta_5450_cropncleaned_edit.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Charles Baudelaire (1846)": {
  "page": "Charles Baudelaire",
  "image": "https://upload.wikimedia.org/wikipedia/commons/1/16/%C3%89tienne_Carjat%2C_Portrait_of_Charles_Baudelaire%2C_circa_1862.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Edvard Munch, The Death of Marat (1907)": {
  "page": "The Death of Marat",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/aa/Death_of_Marat_by_David.jpg/3840px-Death_of_Marat_by_David.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Vik Muniz, Marat (Sebastião) (2008)": {
  "page": "Marat"
 },
 "Édouard Manet, The Execution of Emperor Maximilian (1867 – 69)": {
  "page": "The Execution of Emperor Maximilian",
  "image": "https://upload.wikimedia.org/wikipedia/commons/4/40/Edouard_Manet_022.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Pablo Picasso, Massacre in Korea (1951)": {
  "page": "Massacre in Korea"
 },
 "Goya, The Disasters of War (1810 – 20)": {
  "page": "The Disasters of War",
  "image": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Prado_-_Los_Desastres_de_la_Guerra_-_No._34_-_Por_una_nabaja.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Robert Hughes on the man in white": {
  "page": "The Man in the White Suit"
 },
 "Nietzsche, Kant, and the sublime": {
  "page": "Friedrich Nietzsche",
  "image": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Nietzsche187a.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Ansel Adams and the mountain photograph": {
  "page": "Ansel Adams",
  "image": "https://upload.wikimedia.org/wikipedia/commons/0/05/Ansel_Adams_and_camera.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Beyond: Two Souls, The Truman Show, Dead Poets Society": {
  "page": "Beyond: Two Souls"
 },
 "Michelangelo’s Last Judgement": {
  "page": "The Last Judgment (Michelangelo)",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Last_Judgement_%28Michelangelo%29.jpg/3840px-Last_Judgement_%28Michelangelo%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Eugène Delacroix, The Barque of Dante (1822)": {
  "page": "The Barque of Dante",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e5/Dante_et_Virgile%2C_dit_aussi_La_barque_de_Dante_-_Eug%C3%A8ne_Delacroix_-_Mus%C3%A9e_du_Louvre_Peintures_INV_3820_%3B_L_3837.jpg/3840px-Dante_et_Virgile%2C_dit_aussi_La_barque_de_Dante_-_Eug%C3%A8ne_Delacroix_-_Mus%C3%A9e_du_Louvre_Peintures_INV_3820_%3B_L_3837.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Julian Barnes, A History of the World in 10½ Chapters (1989)": {
  "page": "A History of the World in 10½ Chapters"
 },
 "The Pogues, Asylum Records, Banksy in Calais (2015)": {
  "page": "The Pogues",
  "image": "https://upload.wikimedia.org/wikipedia/commons/6/61/Pogues_Munich_2011.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Géricault, The Raft of the Medusa (1819)": {
  "page": "The Raft of the Medusa",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg/3840px-JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Victor Hugo, Les Misérables (1862)": {
  "page": "Les Misérables",
  "image": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Monsieur_Madeleine_par_Gustave_Brion.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Coldplay, Viva la Vida (2008)": {
  "page": "Viva la Vida"
 },
 "Bartholdi’s Statue of Liberty (1886)": {
  "page": "Statue of Liberty",
  "image": "https://upload.wikimedia.org/wikipedia/commons/8/89/Front_view_of_Statue_of_Liberty_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Claude Debussy, La Mer (1905)": {
  "page": "La mer"
 },
 "Van Gogh, letters (1888)": {
  "page": "The Letters of Vincent van Gogh",
  "image": "https://upload.wikimedia.org/wikipedia/commons/b/be/Letter_from_Vincent_Van_Gogh_to_Theo_Van_Gogh_9_April_1885.jpeg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Rilke, “Der Berg” (1907); the 🌊 emoji": {
  "page": "The Mountain (1991 film)"
 },
 "The 2024 Japanese ¥1000 banknote": {
  "page": "Banknotes of the Japanese yen",
  "image": "https://upload.wikimedia.org/wikipedia/commons/f/f8/Series_F_10000_yen_front.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Thomas Campbell, “Ye Mariners of England”": {
  "page": "Thomas Campbell (poet)",
  "image": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Thomas_Campbell_by_Sir_Thomas_Lawrence.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Skyfall (2012)": {
  "page": "Skyfall"
 },
 "Mike Leigh, Mr. Turner (2014)": {
  "page": "Mr. Turner"
 },
 "Titian/Giorgione, Pastoral Concert (c. 1509); Raimondi after Raphael, Judgement of Paris": {
  "page": "Pastoral Concert",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Le_Concert_champ%C3%AAtre%2C_by_Titian%2C_from_C2RMF_retouchedFXD.jpg/3840px-Le_Concert_champ%C3%AAtre%2C_by_Titian%2C_from_C2RMF_retouchedFXD.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Claude Monet, Le Déjeuner sur l’herbe (1865 – 66)": {
  "page": "Le Déjeuner sur l'herbe",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/90/Edouard_Manet_-_Luncheon_on_the_Grass_-_Google_Art_Project.jpg/3840px-Edouard_Manet_-_Luncheon_on_the_Grass_-_Google_Art_Project.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Pablo Picasso, Déjeuner series (1959 – 62)": {
  "page": "Le Déjeuner sur l'herbe",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/90/Edouard_Manet_-_Luncheon_on_the_Grass_-_Google_Art_Project.jpg/3840px-Edouard_Manet_-_Luncheon_on_the_Grass_-_Google_Art_Project.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Bow Wow Wow, See Jungle! (1981)": {
  "page": "See Jungle! See Jungle! Go Join Your Gang Yeah, City All Over! Go Ape Crazy!"
 },
 "Louis Leroy, Le Charivari (25 April 1874)": {
  "page": "Le Charivari",
  "image": "https://upload.wikimedia.org/wikipedia/commons/9/9b/Le_Charivari.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "J. M. W. Turner": {
  "page": "J. M. W. Turner",
  "image": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Turner_Self_Portrait.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Donald Olson, Texas State University (2014)": {
  "page": "Texas State University"
 },
 "Pablo Picasso, Le Moulin de la Galette (1900)": {
  "page": "Le Moulin de la Galette (Van Gogh series)",
  "image": "https://upload.wikimedia.org/wikipedia/commons/b/b9/Van_Gogh_-_Le_Moulin_de_la_Galette8.jpeg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Toulouse-Lautrec, At the Moulin de la Galette (1889)": {
  "page": "Bal du moulin de la Galette",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Renoir%2C_Pierre-Auguste_-_Dance_at_Le_Moulin_de_la_Galette%2C_1876.jpg/3840px-Renoir%2C_Pierre-Auguste_-_Dance_at_Le_Moulin_de_la_Galette%2C_1876.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Amélie (2001)": {
  "page": "Amélie"
 },
 "Stephen Sondheim, Sunday in the Park with George (1984)": {
  "page": "Sunday in the Park with George"
 },
 "Ferris Bueller’s Day Off (1986)": {
  "page": "Ferris Bueller's Day Off"
 },
 "Chevreul and Ogden Rood on colour": {
  "page": "Ogden Rood",
  "image": "https://upload.wikimedia.org/wikipedia/commons/7/76/PSM_V62_D290_Ogden_Nicholas_Rood.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Every pixel": {
  "page": "Pixel connectivity"
 },
 "Don McLean, “Vincent” (1971)": {
  "page": "Vincent",
  "image": "https://upload.wikimedia.org/wikipedia/commons/8/81/Glorifica%C3%A7%C3%A3o_de_S%C3%A3o_Vicente_%281781%29_-_Pedro_Alexandrino_de_Carvalho.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Loving Vincent (2017)": {
  "page": "Loving Vincent"
 },
 "Kolmogorov turbulence (Aragón et al., 2008)": {
  "page": "Turbulence"
 },
 "Van Gogh’s letter to Theo, June 1889": {
  "page": "Theo van Gogh (art dealer)",
  "image": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Theo_van_Gogh_%281888%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Wes Craven, Scream (1996)": {
  "page": "Scream"
 },
 "The 😱 emoji": {
  "search": "The 😱 emoji"
 },
 "Andy Warhol, The Scream (After Munch) (1984)": {
  "page": "The Scream",
  "image": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Home Alone poster (1990)": {
  "page": "Home Sweet Home Alone"
 },
 "The Le Nain brothers (17th century)": {
  "page": "Le Nain",
  "image": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Louis_Le_Nain-_Happy_Family-_1642-_Louvre.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Picasso and Braque, Cubism (1907 – )": {
  "page": "Cubism",
  "image": "https://upload.wikimedia.org/wikipedia/en/1/1c/Pablo_Picasso%2C_1910%2C_Girl_with_a_Mandolin_%28Fanny_Tellier%29%2C_oil_on_canvas%2C_100.3_x_73.6_cm%2C_Museum_of_Modern_Art_New_York..jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Rilke, Letters on Cézanne (1907)": {
  "page": "Paul Cézanne",
  "image": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Paul-Cezanne.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "The mosaics of San Vitale, Ravenna (6th century)": {
  "page": "Ravenna",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Ravenna_Mausoleo_di_Teodorico_Esterno_08.jpg/3840px-Ravenna_Mausoleo_di_Teodorico_Esterno_08.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Auguste Rodin, The Kiss (1882)": {
  "page": "The Kiss"
 },
 "Austria’s 100-euro gold coin (2003)": {
  "page": "Austrian euro coins"
 },
 "Every gift shop in Europe": {
  "page": "Wii Shop Channel",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Wii_Shop_Channel_SVG.svg/3840px-Wii_Shop_Channel_SVG.svg.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Cézanne, The Large Bathers; Greek red-figure vases": {
  "page": "The Bathers (Cézanne)",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/25/Paul_C%C3%A9zanne%2C_French_-_The_Large_Bathers_-_Google_Art_Project.jpg/3840px-Paul_C%C3%A9zanne%2C_French_-_The_Large_Bathers_-_Google_Art_Project.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Matisse, Le Bonheur de vivre (1906)": {
  "page": "Le bonheur de vivre",
  "image": "https://upload.wikimedia.org/wikipedia/commons/b/b9/Bonheur_Matisse.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Keith Haring’s dancing figures": {
  "page": "Keith Haring",
  "image": "https://upload.wikimedia.org/wikipedia/commons/0/04/Haringpalladium_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Picasso and Matisse: the rivalry": {
  "page": "Pablo Picasso",
  "image": "https://upload.wikimedia.org/wikipedia/commons/9/98/Pablo_picasso_1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Arnold Schoenberg’s atonal music (1911)": {
  "search": "Arnold Schoenberg’s atonal music"
 },
 "Monet, Haystacks (1890 – 91)": {
  "page": "Hay",
  "image": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Roundbale1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Abstract Expressionism": {
  "page": "Abstract expressionism"
 },
 "Alphonse Allais, Combat de nègres dans une cave pendant la nuit (1897)": {
  "search": "Combat de nègres dans une cave pendant la nuit"
 },
 "Ad Reinhardt, Black Paintings (1960s); Rauschenberg’s White Paintings (1951)": {
  "page": "Black Paintings",
  "image": "https://upload.wikimedia.org/wikipedia/commons/f/fb/Quinta_del_Sordo_1900.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Tatlin, Lissitzky, Rodchenko, the Bauhaus": {
  "page": "Vladimir Tatlin",
  "image": "https://upload.wikimedia.org/wikipedia/commons/9/96/%D0%A2%D0%B0%D1%82%D0%BB%D0%B8%D0%BD.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Instagram’s Blackout Tuesday (2020)": {
  "page": "Blackout Tuesday",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/21/Solid_black.svg/3840px-Solid_black.svg.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Yves Saint Laurent, the Mondrian dress (1965)": {
  "page": "Yves Saint Laurent (fashion house)",
  "image": "https://upload.wikimedia.org/wikipedia/commons/0/09/Saint_Laurent_Paris_-_Store_%2851395501701%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Gerrit Rietveld, Red and Blue Chair (1923) and Schröder House (1924)": {
  "page": "Rietveld Schröder House",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/Rietveld_Schr%C3%B6derhuis_HayKranen-20.JPG/3840px-Rietveld_Schr%C3%B6derhuis_HayKranen-20.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Mondrian, Broadway Boogie Woogie (1943)": {
  "page": "Broadway Boogie Woogie",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Piet_Mondrian%2C_1942_-_Broadway_Boogie_Woogie.jpg/3840px-Piet_Mondrian%2C_1942_-_Broadway_Boogie_Woogie.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "L’Oréal, Nike, the Partridge Family bus": {
  "page": "L'Oréal",
  "image": "https://thumb.wikimedia.org/wikipedia/en/thumb/a/a1/Extension_si%C3%A8ge_L%27Or%C3%A9al_%2843707042205%29.jpg/3840px-Extension_si%C3%A8ge_L%27Or%C3%A9al_%2843707042205%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "Jan van Eyck, Hans Memling": {
  "page": "Hans Memling",
  "image": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Hans_Memling_-_Self-portrait.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Gordon Parks, American Gothic (1942)": {
  "page": "American Gothic",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f7/Grant_Wood_-_American_Gothic_%281930%29.jpg/3840px-Grant_Wood_-_American_Gothic_%281930%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 },
 "The Rocky Horror Picture Show, The Simpsons, Green Acres": {
  "page": "The Rocky Horror Picture Show"
 },
 "Beyoncé and Jay-Z, “Apeshit” (2018)": {
  "page": "Apeshit"
 },
 "Ernest Hemingway, “The Killers” (1927)": {
  "page": "The Killers",
  "image": "https://upload.wikimedia.org/wikipedia/commons/a/ae/KillersBST080717-38_%2835742625041%29_%28cropped%29_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled"
 },
 "Ridley Scott, Blade Runner (1982)": {
  "page": "Blade Runner"
 },
 "Gottfried Helnwein, Boulevard of Broken Dreams (1984)": {
  "page": "Boulevard of Broken Dreams"
 },
 "The Simpsons, Banksy, Tom Waits’s Nighthawks at the Diner (1975)": {
  "page": "The Simpsons",
  "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/The_Simpsons_yellow_logo.svg/3840px-The_Simpsons_yellow_logo.svg.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
 }
};
if (typeof window !== 'undefined') window.REFERENCES = REFERENCES;
if (typeof module !== 'undefined') module.exports = { REFERENCES };
