/* Generated by scripts/references.mjs — do not edit by hand.
   Reference labels that resolve to a Wikipedia article about an actual work.
   Labels absent here point at no article worth offering, and render unlinked. */
const REFERENCES = {
 "Velázquez, Las Meninas (1656)": {
  "page": "Las Meninas"
 },
 "Homeric Hymn to Aphrodite; Poliziano’s Stanze": {
  "page": "Homeric Hymns"
 },
 "Adobe Illustrator splash screen (1987 – 2010s)": {
  "page": "Adobe Illustrator"
 },
 "Gospel of John 13:21": {
  "page": "Gospel of John"
 },
 "Andy Warhol, The Last Supper series (1986)": {
  "page": "Last Supper (Warhol)"
 },
 "Luis Buñuel, Viridiana (1961)": {
  "page": "Viridiana"
 },
 "Nat King Cole, “Mona Lisa” (1950)": {
  "page": "Mona Lisa (Nat King Cole song)"
 },
 "E.T. the Extra-Terrestrial poster (1982)": {
  "page": "E.T. the Extra-Terrestrial"
 },
 "Frank Meshberger, JAMA (1990)": {
  "page": "JAMA"
 },
 "Gospel of Matthew 9:9": {
  "page": "Gospel of Matthew"
 },
 "Michelangelo, The Creation of Adam": {
  "page": "The Creation of Adam"
 },
 "Peter Greenaway, Nightwatching (2007)": {
  "page": "Nightwatching"
 },
 "Operation Night Watch (2019 – )": {
  "page": "The Night Watch"
 },
 "Jan van Eyck, The Arnolfini Portrait (1434)": {
  "page": "Arnolfini Portrait"
 },
 "Pablo Picasso, Las Meninas (1957)": {
  "page": "Las Meninas (Picasso)"
 },
 "Michel Foucault, The Order of Things (1966)": {
  "page": "The Order of Things"
 },
 "Tracy Chevalier, Girl with a Pearl Earring (1999); film (2003)": {
  "page": "Girl with a Pearl Earring (film)"
 },
 "Banksy, Girl with a Pierced Eardrum (2014)": {
  "page": "Girl with a Pierced Eardrum"
 },
 "Michelangelo, Pietà (1499)": {
  "page": "Pietà (Michelangelo)"
 },
 "Edvard Munch, The Death of Marat (1907)": {
  "page": "The Death of Marat"
 },
 "Édouard Manet, The Execution of Emperor Maximilian (1867 – 69)": {
  "page": "The Execution of Emperor Maximilian"
 },
 "Pablo Picasso, Massacre in Korea (1951)": {
  "page": "Massacre in Korea"
 },
 "Goya, The Disasters of War (1810 – 20)": {
  "page": "The Disasters of War"
 },
 "Beyond: Two Souls, The Truman Show, Dead Poets Society": {
  "page": "Beyond: Two Souls"
 },
 "Eugène Delacroix, The Barque of Dante (1822)": {
  "page": "The Barque of Dante"
 },
 "Julian Barnes, A History of the World in 10½ Chapters (1989)": {
  "page": "A History of the World in 10½ Chapters"
 },
 "Géricault, The Raft of the Medusa (1819)": {
  "page": "The Raft of the Medusa"
 },
 "Victor Hugo, Les Misérables (1862)": {
  "page": "Les Misérables"
 },
 "Coldplay, Viva la Vida (2008)": {
  "page": "Viva la Vida"
 },
 "Claude Debussy, La Mer (1905)": {
  "page": "La mer"
 },
 "Van Gogh, letters (1888)": {
  "page": "The Letters of Vincent van Gogh"
 },
 "Rilke, “Der Berg” (1907); the 🌊 emoji": {
  "page": "The Mountain (1991 film)"
 },
 "Skyfall (2012)": {
  "page": "Skyfall"
 },
 "Mike Leigh, Mr. Turner (2014)": {
  "page": "Mr. Turner"
 },
 "Titian/Giorgione, Pastoral Concert (c. 1509); Raimondi after Raphael, Judgement of Paris": {
  "page": "Pastoral Concert"
 },
 "Claude Monet, Le Déjeuner sur l’herbe (1865 – 66)": {
  "page": "Le Déjeuner sur l'herbe"
 },
 "Pablo Picasso, Déjeuner series (1959 – 62)": {
  "page": "Le Déjeuner sur l'herbe"
 },
 "Louis Leroy, Le Charivari (25 April 1874)": {
  "page": "Le Charivari"
 },
 "Pablo Picasso, Le Moulin de la Galette (1900)": {
  "page": "Le Moulin de la Galette (Picasso)"
 },
 "Toulouse-Lautrec, At the Moulin de la Galette (1889)": {
  "page": "Bal du moulin de la Galette"
 },
 "Amélie (2001)": {
  "page": "Amélie"
 },
 "Stephen Sondheim, Sunday in the Park with George (1984)": {
  "page": "Sunday in the Park with George"
 },
 "Ferris Bueller’s Day Off (1986)": {
  "page": "Ferris Bueller's Day Off"
 },
 "Don McLean, “Vincent” (1971)": {
  "page": "Vincent (Don McLean song)"
 },
 "Loving Vincent (2017)": {
  "page": "Loving Vincent"
 },
 "Wes Craven, Scream (1996)": {
  "page": "Scream (1996 film)"
 },
 "Andy Warhol, The Scream (After Munch) (1984)": {
  "page": "The Scream"
 },
 "Auguste Rodin, The Kiss (1882)": {
  "page": "The Kiss (Rodin sculpture)"
 },
 "Matisse, Le Bonheur de vivre (1906)": {
  "page": "Le bonheur de vivre"
 },
 "Monet, Haystacks (1890 – 91)": {
  "page": "Haystacks (Monet series)"
 },
 "Ad Reinhardt, Black Paintings (1960s); Rauschenberg’s White Paintings (1951)": {
  "page": "Black Paintings"
 },
 "Yves Saint Laurent, the Mondrian dress (1965)": {
  "page": "Mondrian Collection"
 },
 "Mondrian, Broadway Boogie Woogie (1943)": {
  "page": "Broadway Boogie Woogie"
 },
 "Gordon Parks, American Gothic (1942)": {
  "page": "American Gothic (photograph)"
 },
 "The Rocky Horror Picture Show, The Simpsons, Green Acres": {
  "page": "The Rocky Horror Picture Show"
 },
 "Ernest Hemingway, “The Killers” (1927)": {
  "page": "The Killers (Hemingway short story)"
 },
 "Ridley Scott, Blade Runner (1982)": {
  "page": "Blade Runner (franchise)"
 },
 "Gottfried Helnwein, Boulevard of Broken Dreams (1984)": {
  "page": "Boulevard of Broken Dreams"
 }
};
if (typeof window !== 'undefined') window.REFERENCES = REFERENCES;
if (typeof module !== 'undefined') module.exports = { REFERENCES };
