/* Generated by scripts/references.mjs — do not edit by hand.
   Each reference label mapped to the Wikipedia article that explains it. */
const REFERENCES = {
 "Velázquez, Las Meninas (1656)": {
  "page": "Las Meninas"
 },
 "David Hockney, Secret Knowledge (2001)": {
  "page": "David Hockney"
 },
 "Erwin Panofsky (1934)": {
  "page": "Erwin Panofsky"
 },
 "Homeric Hymn to Aphrodite; Poliziano’s Stanze": {
  "page": "Homeric Hymns"
 },
 "Andy Warhol, Details of Renaissance Paintings (1984)": {
  "page": "Andy Warhol"
 },
 "Adobe Illustrator splash screen (1987 – 2010s)": {
  "page": "Adobe Illustrator"
 },
 "Uma Thurman in The Adventures of Baron Munchausen (1988)": {
  "page": "The Adventures of Baron Munchausen"
 },
 "Gospel of John 13:21": {
  "page": "Gospel of John"
 },
 "Andy Warhol, The Last Supper series (1986)": {
  "page": "Last Supper (Warhol)"
 },
 "Luis Buñuel, Viridiana (1961)": {
  "page": "Viridiana"
 },
 "Dan Brown, The Da Vinci Code (2003)": {
  "page": "The Da Vinci Code"
 },
 "Marcel Duchamp, L.H.O.O.Q. (1919)": {
  "page": "Marcel Duchamp"
 },
 "Andy Warhol, Thirty Are Better Than One (1963)": {
  "page": "Andy Warhol"
 },
 "Nat King Cole, “Mona Lisa” (1950)": {
  "page": "Mona Lisa (Nat King Cole song)"
 },
 "Walter Pater, The Renaissance (1873)": {
  "page": "Walter Pater"
 },
 "Genesis 1:27; Lorenzo Ghiberti’s Gates of Paradise (1425 – 52)": {
  "page": "Image of God"
 },
 "E.T. the Extra-Terrestrial poster (1982)": {
  "page": "E.T. the Extra-Terrestrial"
 },
 "Frank Meshberger, JAMA (1990)": {
  "page": "JAMA"
 },
 "Nokia’s 1990s “Connecting People” logo": {
  "page": "Nokia"
 },
 "Plato, Timaeus; Aristotle, Nicomachean Ethics": {
  "page": "Aristotle"
 },
 "Bramante’s St Peter’s": {
  "page": "Donato Bramante"
 },
 "Pieter Bruegel the Elder": {
  "page": "Pieter Bruegel the Elder"
 },
 "Salvador Dalí and the Surrealists": {
  "page": "Salvador Dalí"
 },
 "Michael Jackson, Dangerous album cover (1991)": {
  "page": "Dangerous (Michael Jackson album)"
 },
 "Gospel of Matthew 9:9": {
  "page": "Gospel of Matthew"
 },
 "Michelangelo, The Creation of Adam": {
  "page": "The Creation of Adam"
 },
 "Rembrandt, Georges de La Tour, Artemisia Gentileschi": {
  "page": "Artemisia Gentileschi"
 },
 "Pope Francis (2013)": {
  "page": "Pope Francis"
 },
 "Frans Hals’s militia pieces": {
  "page": "Frans Hals"
 },
 "Peter Greenaway, Nightwatching (2007)": {
  "page": "Nightwatching"
 },
 "Operation Night Watch (2019 – )": {
  "page": "The Night Watch"
 },
 "Jan van Eyck, The Arnolfini Portrait (1434)": {
  "page": "Arnolfini Portrait"
 },
 "Pablo Picasso, Las Meninas (1957)": {
  "page": "Las Meninas (Picasso)"
 },
 "Michel Foucault, The Order of Things (1966)": {
  "page": "The Order of Things"
 },
 "Salvador Dalí, Francis Bacon, Joel-Peter Witkin": {
  "page": "Salvador Dalí"
 },
 "Tracy Chevalier, Girl with a Pearl Earring (1999); film (2003)": {
  "page": "Girl with a Pearl Earring (film)"
 },
 "Banksy, Girl with a Pierced Eardrum (2014)": {
  "page": "Girl with a Pierced Eardrum"
 },
 "Vermeer, Mauritshuis (2023)": {
  "page": "Mauritshuis"
 },
 "Michelangelo, Pietà (1499)": {
  "page": "Pietà (Michelangelo)"
 },
 "Charles Baudelaire (1846)": {
  "page": "Charles Baudelaire"
 },
 "Edvard Munch, The Death of Marat (1907)": {
  "page": "The Death of Marat"
 },
 "Vik Muniz, Marat (Sebastião) (2008)": {
  "page": "The Death of Marat"
 },
 "Édouard Manet, The Execution of Emperor Maximilian (1867 – 69)": {
  "page": "The Execution of Emperor Maximilian"
 },
 "Pablo Picasso, Massacre in Korea (1951)": {
  "page": "Massacre in Korea"
 },
 "Goya, The Disasters of War (1810 – 20)": {
  "page": "The Disasters of War"
 },
 "Robert Hughes on the man in white": {
  "page": "The Man in the White Suit"
 },
 "Nietzsche, Kant, and the sublime": {
  "page": "Friedrich Nietzsche"
 },
 "Ansel Adams and the mountain photograph": {
  "page": "Ansel Adams"
 },
 "Beyond: Two Souls, The Truman Show, Dead Poets Society": {
  "page": "Beyond: Two Souls"
 },
 "Michelangelo’s Last Judgement": {
  "page": "Michelangelo"
 },
 "Eugène Delacroix, The Barque of Dante (1822)": {
  "page": "The Barque of Dante"
 },
 "Julian Barnes, A History of the World in 10½ Chapters (1989)": {
  "page": "A History of the World in 10½ Chapters"
 },
 "The Pogues, Asylum Records, Banksy in Calais (2015)": {
  "page": "The Pogues"
 },
 "Géricault, The Raft of the Medusa (1819)": {
  "page": "The Raft of the Medusa"
 },
 "Victor Hugo, Les Misérables (1862)": {
  "page": "Les Misérables"
 },
 "Coldplay, Viva la Vida (2008)": {
  "page": "Viva la Vida"
 },
 "Bartholdi’s Statue of Liberty (1886)": {
  "page": "Statue of Liberty"
 },
 "Claude Debussy, La Mer (1905)": {
  "page": "La mer"
 },
 "Van Gogh, letters (1888)": {
  "page": "The Letters of Vincent van Gogh"
 },
 "Rilke, “Der Berg” (1907); the 🌊 emoji": {
  "page": "The Mountain (1991 film)"
 },
 "The 2024 Japanese ¥1000 banknote": {
  "page": "Banknotes of the Japanese yen"
 },
 "Thomas Campbell, “Ye Mariners of England”": {
  "page": "Thomas Campbell (poet)"
 },
 "Skyfall (2012)": {
  "page": "Skyfall"
 },
 "Mike Leigh, Mr. Turner (2014)": {
  "page": "Mr. Turner"
 },
 "Titian/Giorgione, Pastoral Concert (c. 1509); Raimondi after Raphael, Judgement of Paris": {
  "page": "Pastoral Concert"
 },
 "Claude Monet, Le Déjeuner sur l’herbe (1865 – 66)": {
  "page": "Le Déjeuner sur l'herbe"
 },
 "Pablo Picasso, Déjeuner series (1959 – 62)": {
  "page": "Le Déjeuner sur l'herbe"
 },
 "Bow Wow Wow, See Jungle! (1981)": {
  "page": "See Jungle! See Jungle! Go Join Your Gang Yeah, City All Over! Go Ape Crazy!"
 },
 "Louis Leroy, Le Charivari (25 April 1874)": {
  "page": "Le Charivari"
 },
 "J. M. W. Turner": {
  "page": "J. M. W. Turner"
 },
 "Donald Olson, Texas State University (2014)": {
  "page": "Texas"
 },
 "Pablo Picasso, Le Moulin de la Galette (1900)": {
  "page": "Le Moulin de la Galette (Picasso)"
 },
 "Toulouse-Lautrec, At the Moulin de la Galette (1889)": {
  "page": "Bal du moulin de la Galette"
 },
 "Amélie (2001)": {
  "page": "Amélie"
 },
 "Stephen Sondheim, Sunday in the Park with George (1984)": {
  "page": "Sunday in the Park with George"
 },
 "Ferris Bueller’s Day Off (1986)": {
  "page": "Ferris Bueller's Day Off"
 },
 "Chevreul and Ogden Rood on colour": {
  "page": "Ogden Rood"
 },
 "Every pixel": {
  "page": "Pixel 11"
 },
 "Don McLean, “Vincent” (1971)": {
  "page": "Vincent (Don McLean song)"
 },
 "Loving Vincent (2017)": {
  "page": "Loving Vincent"
 },
 "Kolmogorov turbulence (Aragón et al., 2008)": {
  "page": "Turbulence"
 },
 "Van Gogh’s letter to Theo, June 1889": {
  "page": "Theo van Gogh (art dealer)"
 },
 "Wes Craven, Scream (1996)": {
  "page": "Scream (1996 film)"
 },
 "The 😱 emoji": {
  "page": "Apple Color Emoji"
 },
 "Andy Warhol, The Scream (After Munch) (1984)": {
  "page": "The Scream"
 },
 "Home Alone poster (1990)": {
  "page": "Home Alone"
 },
 "The Le Nain brothers (17th century)": {
  "page": "Le Nain"
 },
 "Picasso and Braque, Cubism (1907 – )": {
  "page": "Cubism"
 },
 "Rilke, Letters on Cézanne (1907)": {
  "page": "Paul Cézanne"
 },
 "The mosaics of San Vitale, Ravenna (6th century)": {
  "page": "Ravenna"
 },
 "Auguste Rodin, The Kiss (1882)": {
  "page": "The Kiss (Rodin sculpture)"
 },
 "Austria’s 100-euro gold coin (2003)": {
  "page": "1 euro coin"
 },
 "Every gift shop in Europe": {
  "page": "Wii Shop Channel"
 },
 "Matisse, Le Bonheur de vivre (1906)": {
  "page": "Le bonheur de vivre"
 },
 "Keith Haring’s dancing figures": {
  "page": "Keith Haring"
 },
 "Picasso and Matisse: the rivalry": {
  "page": "Pablo Picasso"
 },
 "Arnold Schoenberg’s atonal music (1911)": {
  "page": "Arnold Schoenberg"
 },
 "Monet, Haystacks (1890 – 91)": {
  "page": "Haystacks (Monet series)"
 },
 "Abstract Expressionism": {
  "page": "Abstract expressionism"
 },
 "Ad Reinhardt, Black Paintings (1960s); Rauschenberg’s White Paintings (1951)": {
  "page": "Black Paintings"
 },
 "Tatlin, Lissitzky, Rodchenko, the Bauhaus": {
  "page": "El Lissitzky"
 },
 "Instagram’s Blackout Tuesday (2020)": {
  "page": "Blackout Tuesday"
 },
 "Yves Saint Laurent, the Mondrian dress (1965)": {
  "page": "Mondrian Collection"
 },
 "Gerrit Rietveld, Red and Blue Chair (1923) and Schröder House (1924)": {
  "page": "Red and Blue Chair"
 },
 "Mondrian, Broadway Boogie Woogie (1943)": {
  "page": "Broadway Boogie Woogie"
 },
 "L’Oréal, Nike, the Partridge Family bus": {
  "page": "L'Oréal"
 },
 "Jan van Eyck, Hans Memling": {
  "page": "Hans Memling"
 },
 "Gordon Parks, American Gothic (1942)": {
  "page": "American Gothic (photograph)"
 },
 "The Rocky Horror Picture Show, The Simpsons, Green Acres": {
  "page": "The Rocky Horror Picture Show"
 },
 "Beyoncé and Jay-Z, “Apeshit” (2018)": {
  "page": "Apeshit"
 },
 "Ernest Hemingway, “The Killers” (1927)": {
  "page": "The Killers (Hemingway short story)"
 },
 "Ridley Scott, Blade Runner (1982)": {
  "page": "Blade Runner (franchise)"
 },
 "Gottfried Helnwein, Boulevard of Broken Dreams (1984)": {
  "page": "Boulevard of Broken Dreams"
 },
 "The Simpsons, Banksy, Tom Waits’s Nighthawks at the Diner (1975)": {
  "page": "Nighthawks (Hopper)"
 }
};
if (typeof window !== 'undefined') window.REFERENCES = REFERENCES;
if (typeof module !== 'undefined') module.exports = { REFERENCES };
