import {parts,groups,findParts} from './components.js';
import {createWatch} from './model.js';
const $=s=>document.querySelector(s);let model,selected=null;
const list=$('#component-list');
// Each row shows or hides one part; each section header shows or hides the whole section.
for(const category of groups){const group=document.createElement('div');group.className='group';const members=parts.filter(p=>p.category===category);const title=document.createElement('button');title.className='group-title';title.innerHTML='<span></span><span class="check" aria-hidden="true"></span>';title.firstChild.textContent=category;title.setAttribute('aria-label',`Show all ${category} parts`);title.onclick=()=>{model?.setVisible(members.map(p=>p.id),title.getAttribute('aria-pressed')!=='true');syncVisibility()};group.append(title);for(const p of members){const row=document.createElement('button');row.className='component-row';row.dataset.id=p.id;row.dataset.category=p.category;row.innerHTML='<span class="part-dot" aria-hidden="true"></span><span class="part-name"></span><span class="check" aria-hidden="true"></span>';row.querySelector('.part-name').textContent=p.name;row.setAttribute('aria-label',`Show ${p.name}`);row.onclick=()=>{model?.toggle(p.id);syncVisibility()};group.append(row)}list.append(group)}
function syncVisibility(){document.querySelectorAll('.group').forEach(group=>{const rows=[...group.querySelectorAll('.component-row')];let shown=0;for(const row of rows){const visible=model?.isVisible(row.dataset.id)??true;row.setAttribute('aria-pressed',String(visible));if(visible)shown++}group.querySelector('.group-title').setAttribute('aria-pressed',shown===rows.length?'true':shown?'mixed':'false')});$('#clear-all').textContent=anyVisible()?'Clear all':'Select all'}
// Clear all hides every part; once nothing is shown, the same button brings everything back.
const anyVisible=()=>parts.some(p=>model?.isVisible(p.id)??true);
function select(id,options){const p=parts.find(p=>p.id===id);if(!p)return false;selected=id;model?.select(id,options);$('#detail').hidden=false;document.body.classList.add('detail-open');$('#detail-category').textContent=p.category;$('#detail-title').textContent=p.name;$('#detail-summary').textContent=p.summary;$('#detail-what').textContent=p.what;$('#detail-role').textContent=p.role;$('#detail-how').textContent=p.how;$('#connection-list').hidden=true;$('#connections').textContent='Show connected parts';$('#connection-list').replaceChildren();for(const link of p.links){const connected=parts.find(x=>x.id===link);const b=document.createElement('button');b.textContent=connected.name;b.onclick=()=>select(link);$('#connection-list').append(b)}document.querySelectorAll('.component-row').forEach(row=>row.classList.toggle('selected',row.dataset.id===id));$('#search-results').hidden=true;syncVisibility();return true}
function clear(){selected=null;model?.select(null);$('#detail').hidden=true;document.body.classList.remove('detail-open');document.querySelectorAll('.component-row').forEach(row=>row.classList.remove('selected'))}
$('#detail-close').onclick=clear;$('#clear-all').onclick=()=>{const show=!anyVisible();if(!show)clear();model?.setVisible(parts.map(p=>p.id),show);syncVisibility()};$('#focus-part').onclick=()=>selected&&model?.focus(selected);$('#connections').onclick=()=>{$('#connection-list').hidden=!$('#connection-list').hidden;$('#connections').textContent=$('#connection-list').hidden?'Show connected parts':'Hide connected parts'};
const search=$('#search'),results=$('#search-results');function updateSearch(){const q=search.value.trim();results.replaceChildren();if(!q){results.hidden=true;return}const matches=findParts(q);results.hidden=false;if(!matches.length){const p=document.createElement('p');p.textContent='No components found. Try “spring” or “seconds”.';results.append(p);return}for(const p of matches){const button=document.createElement('button');const label=document.createElement('span');label.textContent=p.name;const meta=document.createElement('small');meta.textContent=p.category;button.append(label,meta);button.onclick=()=>{select(p.id);search.value=p.name;search.focus()};results.append(button)}}search.oninput=updateSearch;search.onfocus=()=>{if(search.value)updateSearch()};search.onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();results.querySelector('button')?.focus()}if(e.key==='Enter'){const match=findParts(search.value)[0];if(match){select(match.id);search.value=match.name}}if(e.key==='Escape'){results.hidden=true;search.blur()}};results.onkeydown=e=>{const buttons=[...results.querySelectorAll('button')],i=buttons.indexOf(document.activeElement);if(e.key==='ArrowDown'){e.preventDefault();buttons[(i+1)%buttons.length]?.focus()}if(e.key==='ArrowUp'){e.preventDefault();if(i===0)search.focus();else buttons[i-1]?.focus()}if(e.key==='Escape'){results.hidden=true;search.focus()}};document.addEventListener('pointerdown',e=>{if(!e.target.closest('.search-wrap'))results.hidden=true});
function playUI(){const playing=model?.isPlaying()??false;$('#play').textContent=playing?'Ⅱ':'▶';$('#play').setAttribute('aria-label',playing?'Pause animation':'Play animation')}
$('#play').onclick=()=>{model?.setPlaying(!model.isPlaying());playUI()};$('#step').onclick=()=>{model?.step();playUI()};$('#speed').onchange=e=>model?.setSpeed(Number(e.target.value));$('#explode').oninput=e=>{const v=Number(e.target.value);$('#explode-value').textContent=`${v}%`;model?.setExplode(v/100)};
const about=$('#about');$('#about-open').onclick=()=>about.showModal();$('#about-close').onclick=()=>about.close();about.addEventListener('click',e=>{if(e.target===about){const r=about.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)about.close()}});
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.key==='/'){e.preventDefault();search.focus()}if(e.key==='Escape'){if(about.open)about.close();else clear()}if(e.code==='Space'&&document.activeElement===document.body&&!about.open){e.preventDefault();$('#play').click()}});
// Tapping empty space around the watch clears the selection.
try{model=createWatch($('#viewport'),select,clear);$('#loading').hidden=true;syncVisibility();playUI()}catch(error){$('#loading').hidden=true;$('#error').hidden=false;console.error('Watch rendering failed',error);document.querySelectorAll('.transport button,.transport input,.transport select,#clear-all,#focus-part,.component-row,.group-title').forEach(b=>b.disabled=true)}
// The same search and selection actions are available to supporting agents.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const specs=[{name:'find_watch_components',description:'Find watch components by name, synonym, or role.',inputSchema:{type:'object',properties:{query:{type:'string',minLength:1}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input.query!=='string'||!input.query.trim())throw new Error('A nonempty query is required.');return{components:findParts(input.query).map(({id,name,category})=>({id,name,category}))}}},{name:'inspect_watch_component',description:'Select a component in the watch model and open its description.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.id!=='string'||!parts.some(p=>p.id===input.id))throw new Error('Unknown watch component.');select(input.id);return{selected,descriptionVisible:!$('#detail').hidden,modelAvailable:!!model}}}];for(const tool of specs){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
