export const parts = [
{id:'crown',name:'Crown and stem',category:'Winding and power',alias:'winding knob shaft',summary:'Where your energy enters the watch.',what:'The external knob and the shaft that reaches into the movement.',role:'Let you wind the mainspring and set the hands.',how:'Turning the crown rotates the stem. With the crown pushed in, the winding gears tighten the mainspring; pulling it out switches the mechanism to time setting.',links:['keyless','winding']},
{id:'keyless',name:'Keyless works',category:'Winding and power',alias:'clutch sliding pinion setting lever yoke',summary:'One crown. Two jobs.',what:'A sliding clutch, small gears, and levers connected to the stem.',role:'Switch the crown between winding the watch and setting the time.',how:'Pulling the stem moves a lever and yoke, shifting the clutch into the setting gears. Pushing it back engages the winding train.',links:['crown','winding','cannon']},
{id:'winding',name:'Winding wheels',category:'Winding and power',alias:'crown wheel ratchet wheel winding gears',summary:'A turn of the crown becomes stored power.',what:'The crown wheel and ratchet wheel above the barrel.',role:'Transfer winding effort to the mainspring’s central arbor.',how:'The crown wheel turns the ratchet wheel, which is fixed to the barrel arbor. Rotating the arbor coils the mainspring more tightly.',links:['crown','click','barrel','mainspring']},
{id:'click',name:'Click and spring',category:'Winding and power',alias:'pawl ratchet catch click spring',summary:'The catch that holds a full wind.',what:'A small pivoting catch held against the ratchet wheel by a spring.',role:'Prevent the mainspring from unwinding backward through the winding gears.',how:'The click rides over the ratchet teeth while winding, then catches against a tooth when you stop. Its spring keeps it engaged.',links:['winding','barrel']},
{id:'mainspring',name:'Mainspring',category:'Winding and power',alias:'power reserve spring energy',summary:'The watch’s mechanical energy store.',what:'A long strip of spring metal coiled inside the barrel.',role:'Store energy from winding and release it to power the movement.',how:'Winding tightens the spring around the arbor. As it relaxes, it pushes against the barrel wall, turning the drum and driving the gear train.',links:['barrel','winding','centre']},
{id:'barrel',name:'Barrel and arbor',category:'Winding and power',alias:'drum shaft spring barrel',summary:'A slow-turning drum that drives the train.',what:'A toothed drum containing the mainspring, with a central winding shaft called the arbor.',role:'House the spring and deliver its torque to the first gear.',how:'The mainspring connects the arbor to the barrel wall. With the arbor held by the ratchet, the unwinding spring rotates the drum. The barrel’s teeth drive the centre-wheel pinion.',links:['mainspring','centre','winding']},
{id:'centre',name:'Centre wheel',category:'Gear train',alias:'center second wheel minute gear',summary:'One revolution. One hour.',what:'The first wheel-and-pinion assembly driven by the barrel.',role:'Pass power along the train and provide the minute-rate rotation.',how:'The barrel turns its small pinion. The larger wheel drives the third-wheel pinion. In this model, the centre wheel turns once per hour and carries the friction-fitted cannon pinion.',links:['barrel','third','cannon']},
{id:'third',name:'Third wheel',category:'Gear train',alias:'intermediate gear pinion',summary:'The link between minutes and seconds.',what:'An intermediate wheel and pinion between the centre and fourth wheels.',role:'Transmit power and increase the rotational speed of the train.',how:'The centre wheel drives its pinion; its larger wheel drives the fourth-wheel pinion. In this model, it turns once every ten minutes.',links:['centre','fourth']},
{id:'fourth',name:'Fourth wheel',category:'Gear train',alias:'seconds wheel small seconds',summary:'A minute, measured in one full turn.',what:'The gear-train wheel carrying the small-seconds hand.',role:'Drive the seconds display and pass power to the escape wheel.',how:'It makes one revolution per minute. Its shaft carries the seconds hand on the dial side, while its teeth drive the escape-wheel pinion.',links:['third','escape','hands']},
{id:'escape',name:'Escape wheel',category:'Regulation',alias:'escapement teeth locking impulse',summary:'Continuous power, released a little at a time.',what:'A wheel with fifteen specially shaped teeth at the end of the gear train.',role:'Deliver power to the escapement in controlled increments.',how:'Its teeth alternately lock against and push on the two pallet stones. When the balance unlocks the fork, the wheel advances and delivers an impulse before locking again.',links:['fourth','fork']},
{id:'fork',name:'Pallet fork',category:'Regulation',alias:'pallet stones lever escapement anchor ruby',summary:'The tiny gatekeeper behind every tick.',what:'A pivoting lever with two jewel pallets at one end and a fork at the other.',role:'Lock and release the escape wheel, and transfer impulses to the balance.',how:'The balance’s impulse jewel moves the fork to unlock a pallet. An escape-wheel tooth then pushes that pallet, returning energy through the fork to the balance. The opposite pallet locks the wheel.',links:['escape','roller','balance']},
{id:'roller',name:'Roller and impulse jewel',category:'Regulation',alias:'roller table impulse pin safety roller',summary:'The handshake between fork and balance.',what:'A small disc and projecting jewel attached to the balance staff.',role:'Connect the balance’s oscillation to the pallet fork.',how:'Near the middle of each swing, the jewel enters the fork, unlocks the escapement, and receives an impulse. It then leaves the fork so the balance can swing freely.',links:['fork','balance']},
{id:'balance',name:'Balance wheel',category:'Regulation',alias:'oscillator regulating wheel balance staff',summary:'The rhythm at the heart of the watch.',what:'A weighted wheel that oscillates back and forth on a fine shaft.',role:'Set the timing rhythm together with the hairspring.',how:'Its inertia carries it through each swing while the hairspring pulls it back. Small impulses from the escapement replace lost energy. This model uses 2.5 full oscillations, or five beats, per second.',links:['hairspring','roller','fork','jewels']},
{id:'hairspring',name:'Hairspring',category:'Regulation',alias:'balance spring spiral oscillator',summary:'A spring that gives every swing its return.',what:'A very fine spiral spring attached to the balance staff and a fixed outer stud.',role:'Provide the restoring force that makes the balance oscillate.',how:'The spiral coils and uncoils as the balance turns. Its elasticity pulls the wheel toward its resting position; that restoring force and the balance’s inertia determine the rhythm.',links:['balance','roller']},
{id:'cannon',name:'Cannon pinion',category:'Time display',alias:'minute hand friction sleeve',summary:'Driven by the train. Adjustable by hand.',what:'A friction-fitted sleeve on the centre-wheel shaft that carries the minute hand.',role:'Drive the hands while still allowing you to set the time.',how:'Friction makes it turn with the centre wheel during normal running. When you set the hands, it can slip against the shaft rather than forcing the entire train to move.',links:['centre','motion','hands','keyless']},
{id:'motion',name:'Motion works',category:'Time display',alias:'minute wheel hour wheel reduction gears',summary:'Twelve turns of the minute hand. One of the hour.',what:'The minute wheel and hour wheel beneath the dial.',role:'Reduce the minute-rate rotation to the hour-rate rotation.',how:'The cannon pinion drives the minute wheel. The minute-wheel pinion drives the hour wheel through a combined 12:1 reduction, giving one hour-hand revolution every twelve hours.',links:['cannon','hands']},
{id:'hands',name:'Hands and dial',category:'Time display',alias:'face hour minute second seconds pointers',summary:'The mechanism becomes readable time.',what:'The marked watch face and its hour, minute, and small-seconds pointers.',role:'Display the passage of time.',how:'The hour and minute hands turn on concentric shafts. The small-seconds hand turns on the fourth-wheel shaft, completing one circuit each minute.',links:['cannon','motion','fourth']},
{id:'plates',name:'Mainplate and bridges',category:'Structure',alias:'plate bridge support frame screws',summary:'The structure that keeps everything in place.',what:'The movement’s base plate and the supports above its moving parts.',role:'Keep the gear shafts accurately aligned.',how:'The mainplate and bridges support opposite ends of the pivots. Precisely spaced bearings keep gears meshed while leaving them free to rotate.',links:['jewels','centre','barrel','balance']},
{id:'jewels',name:'Jewels and shock protection',category:'Structure',alias:'ruby bearings incabloc pivots anti shock',summary:'Tiny bearings with an important job.',what:'Hard, polished synthetic jewel bearings and resilient balance-bearing mounts.',role:'Reduce pivot wear and protect the delicate balance staff.',how:'Pivots rotate in polished jewel holes with a small amount of lubricant. The balance’s spring-mounted jewel settings can shift under an impact, then return to position.',links:['plates','balance']},
{id:'case',name:'Case and crystal',category:'Structure',alias:'glass sapphire housing cover bezel',summary:'A protective home for the movement.',what:'The outer housing, bezel, and transparent cover.',role:'Protect the mechanism while keeping the dial visible.',how:'The case encloses and supports the movement; the crystal covers the dial. Hide these layers or separate the assembly to inspect what is usually concealed.',links:['plates','hands']}
];
export const groups=['Winding and power','Gear train','Regulation','Time display','Structure'];
export function findParts(query){const q=query.toLowerCase().trim();return parts.filter(p=>`${p.name} ${p.alias} ${p.role}`.toLowerCase().includes(q));}
